### ISSUE TITLE
Professionals implementation

### ISSUE THREAD

**Issue by dbertranou** [pangolinsw/asclepy#12]
We should create a Professional model that represents the physician that diagnoses the patient and provides the services.

It should have:
- an identity code
- his/her name

Data should be exposed by two endpoints:

/patients:
            GET: returns a list of all professionals
            POST: creates a new professional
/patients/{id}:
            GET: returns a specific professional
            PUT: edits professional data

**Comment by eliasjuanpablo** [comment]
Closed (see #17)

**Comment by eliasjuanpablo** [comment]
Closed (see #17)
