### ISSUE TITLE
Use marshmallow's error messages in flask's abort()

### ISSUE THREAD

**Issue by eliasjuanpablo** [pangolinsw/asclepy#16]
When, for example, we return a Bad Request error with abort(400), we should add the validation errors messages that marshmallow provides.

To accomplish this, we may create an "errors" blueprint to declare handlers that generate this kind of responses.

**Comment by eliasjuanpablo** [comment]
NOTE: we should also take advantage of the error messages and use them in tests assertions

**Comment by dbertranou** [comment]
Closed (see #25)
