### ISSUE TITLE
Patients implementation

### ISSUE THREAD

**Issue by eliasjuanpablo** [pangolinsw/asclepy#8]
We should create a Patient model that represents people attending the healthcare organizations and being diagnosed.

It should have:
    - a unique identifier for the person's identity
    - his/her name
    - gender
    - sex (for statistical purposes)
    - birth date (for statistical purposes)
    - probably a photo? TBD

Data should be exposed by two endpoints:
* /patients:
            POST: creates a new patient
            GET: returns a list of all patients
* /patients/{id}:
            GET: returns a specific patient
            PUT: edits patient data

**Comment by dbertranou** [comment]
Closed (see #18 )
